# Generated by Django 3.2.12 on 2022-04-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='file',
            field=models.ImageField(upload_to='media'),
        ),
    ]
