# Generated by Django 3.2.12 on 2022-04-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220411_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='food_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
